# Generated by Django 4.2 on 2024-10-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entity Types',
                'db_table': 'entity_type',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the filter is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='PlantEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.entitytype')),
            ],
            options={
                'verbose_name_plural': 'Plant Entities',
                'db_table': 'plant_entity',
            },
        ),
        migrations.AddField(
            model_name='entitytype',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
