# Generated by Django 4.2 on 2024-10-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenant',
            table='wa_tenant',
        ),
    ]
