# Generated by Django 4.2 on 2024-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantstoragesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French')], max_length=100, null=True),
        ),
    ]
