# Generated by Django 4.2 on 2024-12-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_default_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_box_name', models.CharField(max_length=255)),
                ('sensor_box_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('plant_entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.plantentity')),
            ],
            options={
                'verbose_name_plural': 'Sensor Boxes',
                'db_table': 'sensor_box',
                'unique_together': {('plant_entity', 'sensor_box_name')},
            },
        ),
    ]
