# Generated by Django 4.2 on 2025-02-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_sensorbox_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=255)),
                ('camera_position', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='tenants.sensorbox')),
            ],
            options={
                'verbose_name_plural': 'Cameras',
                'db_table': 'cameras',
                'unique_together': {('sensor_box', 'camera_id')},
            },
        ),
    ]
