# Generated by Django 4.2 on 2024-10-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_rename_plant_entitytype_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=255, unique=True)),
                ('delivery_start', models.DateTimeField()),
                ('delivery_end', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.plantentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='FlagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Flag Types',
                'db_table': 'flag_type',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('media_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=100)),
                ('media_url', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='TenantFlagDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deployed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.flagtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flag_deployments', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Tenant Flag Deployments',
                'db_table': 'tenant_flag_deployment',
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(max_length=7)),
                ('unicode_char', models.CharField(blank=True, null=True)),
                ('flag_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='severities', to='acceptance_control.flagtype')),
            ],
            options={
                'verbose_name_plural': 'Severity',
                'db_table': 'severity',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.delivery')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.media')),
            ],
            options={
                'verbose_name_plural': 'Delivery Media',
                'db_table': 'delivery_media',
            },
        ),
        migrations.CreateModel(
            name='DeliveryFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flags', to='acceptance_control.delivery')),
                ('flag_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.flagtype')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.severity')),
            ],
            options={
                'verbose_name_plural': 'Delivery Flags',
                'db_table': 'delivery_flag',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_uid', models.CharField(max_length=255)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.plantentity')),
                ('flag_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.flagtype')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.severity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Alarms',
                'db_table': 'alarm',
            },
        ),
    ]
