# Generated by Django 4.2 on 2024-10-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='event_uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
