# Generated by Django 4.2 on 2024-10-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0002_alter_alarm_event_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.alarm')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.media')),
            ],
            options={
                'verbose_name_plural': 'Alarm Media',
                'db_table': 'alarm_media',
            },
        ),
    ]
