# Generated by Django 4.2 on 2024-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0004_flagtypelocalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryERPAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('source_reference', models.CharField(blank=True, help_text='Optional reference to external source or entry', max_length=255, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, help_text='Timestamp for API data retrieval', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery ERP Attachments',
                'db_table': 'delivery_erp_attachment',
            },
        ),
    ]
