# Generated by Django 4.2 on 2024-11-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0007_alarm_ack_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='exclude_from_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarm',
            name='feedback_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarm',
            name='is_actual_alarm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlarmFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_actual_alarm', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.alarm')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.severity')),
            ],
            options={
                'verbose_name': 'Alarm Feedback',
                'verbose_name_plural': 'Alarm Feedbacks',
                'db_table': 'alarm_feedback',
            },
        ),
    ]
