# Generated by Django 4.2 on 2024-12-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_sensorbox'),
        ('acceptance_control', '0008_alarm_exclude_from_dashboard_alarm_feedback_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='sensor_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tenants.sensorbox'),
        ),
    ]
