# Generated by Django 4.2 on 2024-12-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_tenanttablefilter_default'),
        ('acceptance_control', '0009_media_sensor_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='meta_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AlarmAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alarm_attr', to='acceptance_control.alarm')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.datatype')),
            ],
            options={
                'verbose_name_plural': 'Alarm Attribute',
                'db_table': 'alarm_attr',
            },
        ),
    ]
