# Generated by Django 4.2 on 2025-02-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_camera'),
        ('acceptance_control', '0011_deliveryflag_event_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='tenants.camera')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.plantentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Video Archive',
                'verbose_name_plural': 'Video Archives',
                'db_table': 'video_archive',
            },
        ),
        migrations.CreateModel(
            name='VideoArchiveMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.media')),
                ('video_archive', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='acceptance_control.videoarchive')),
            ],
            options={
                'verbose_name_plural': 'Video Archive Media',
                'db_table': 'video_archive_media',
            },
        ),
    ]
