# Generated by Django 4.2 on 2025-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0012_videoarchive_videoarchivemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-going', 'Active'), ('done', 'Done')], default='pending', max_length=255, null=True),
        ),
    ]
