# Generated by Django 4.2 on 2025-03-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0013_delivery_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
