# Generated by Django 4.2 on 2025-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0014_delivery_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmfeedback',
            name='contains_other_object',
            field=models.BooleanField(default=False, help_text='Check if the event contains another object.'),
        ),
    ]
