# Generated by Django 4.2 on 2025-07-22 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0019_taggroup_tag'),
        ('acceptance_control', '0015_alarmfeedback_contains_other_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('human', 'Human'), ('model', 'Model')], default='auto', max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_tags', to='acceptance_control.alarm')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_alarm', to='metadata.tag')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alarm Tags',
                'db_table': 'alarm_tag',
            },
        ),
        migrations.AddIndex(
            model_name='alarmtag',
            index=models.Index(fields=['tag'], name='alarm_tag_tag_id_641301_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmtag',
            index=models.Index(fields=['alarm'], name='alarm_tag_alarm_i_35e579_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alarmtag',
            unique_together={('alarm', 'tag')},
        ),
    ]
