# Generated by Django 4.2 on 2025-07-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_control', '0016_alarmtag_alarmtag_alarm_tag_tag_id_641301_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmtag',
            name='tagged_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
