# Generated by Django 4.2 on 2024-10-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('desciption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Data Types',
                'db_table': 'data_type',
            },
        ),
        migrations.CreateModel(
            name='FieldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_position', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Field Orders',
                'db_table': 'field_order',
            },
        ),
        migrations.CreateModel(
            name='FilterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(help_text="The internal key for the filter item (e.g., 'impurity').", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the filter item is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Filter Items',
                'db_table': 'filter_item',
            },
        ),
        migrations.CreateModel(
            name='FilterItemLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_value', models.CharField(help_text='Localized value of the filter item.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Filter Item Localizations',
                'db_table': 'filter_item_localization',
            },
        ),
        migrations.CreateModel(
            name='FilterLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Localized title of the filter.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Localized description of the filter.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Filter Localizations',
                'db_table': 'filter_localization',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Table Fields',
                'db_table': 'table_field',
            },
        ),
        migrations.CreateModel(
            name='TableFieldLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Localized title of the column.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Localized description of the column.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Table Field Localizations',
                'db_table': 'table_field_localization',
            },
        ),
        migrations.CreateModel(
            name='TableFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(help_text='The internal name of the filter.', max_length=255)),
                ('type', models.CharField(help_text="The data type of the filter (e.g., 'enum').", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the filter is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Table Filters',
                'db_table': 'table filter',
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desciption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Table Type',
                'verbose_name_plural': 'Table Types',
                'db_table': 'table_type',
            },
        ),
        migrations.CreateModel(
            name='TenantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('table_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tabletype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Tenant Tables',
                'db_table': 'tenant_table',
            },
        ),
        migrations.CreateModel(
            name='TenantTableFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the filter item is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.fieldorder')),
                ('table_filter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tablefilter')),
                ('tenant_table', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tenanttable')),
            ],
            options={
                'verbose_name_plural': 'Tenant Table Filters',
                'db_table': 'tenant_table_filter',
            },
        ),
        migrations.CreateModel(
            name='TenantTableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tablefield')),
                ('field_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.fieldorder')),
                ('tenant_table', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tenanttable')),
            ],
            options={
                'verbose_name_plural': 'Tenant Table Fields',
                'db_table': 'tenant_table_field',
            },
        ),
        migrations.AddIndex(
            model_name='tablefilter',
            index=models.Index(fields=['filter_name'], name='table filte_filter__a7e7c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablefilter',
            unique_together={('filter_name',)},
        ),
        migrations.AddField(
            model_name='tablefieldlocalization',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='table_field_localizations', to='metadata.tablefield'),
        ),
        migrations.AddField(
            model_name='tablefieldlocalization',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language'),
        ),
        migrations.AddField(
            model_name='tablefield',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.datatype'),
        ),
        migrations.AddField(
            model_name='filterlocalization',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language'),
        ),
        migrations.AddField(
            model_name='filterlocalization',
            name='table_filter',
            field=models.ForeignKey(help_text='The filter being localized.', on_delete=django.db.models.deletion.RESTRICT, related_name='localizations', to='metadata.tablefilter'),
        ),
        migrations.AddField(
            model_name='filteritemlocalization',
            name='filter_item',
            field=models.ForeignKey(help_text='The filter item being localized.', on_delete=django.db.models.deletion.RESTRICT, related_name='localizations', to='metadata.filteritem'),
        ),
        migrations.AddField(
            model_name='filteritemlocalization',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language'),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='table_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tablefilter'),
        ),
        migrations.AddIndex(
            model_name='tablefieldlocalization',
            index=models.Index(fields=['field', 'language'], name='table_field_field_i_1eee91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablefieldlocalization',
            unique_together={('field', 'language')},
        ),
        migrations.AddIndex(
            model_name='filterlocalization',
            index=models.Index(fields=['table_filter', 'language'], name='filter_loca_table_f_37e73b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filterlocalization',
            unique_together={('table_filter', 'language')},
        ),
        migrations.AddIndex(
            model_name='filteritemlocalization',
            index=models.Index(fields=['filter_item', 'language'], name='filter_item_filter__9b56d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filteritemlocalization',
            unique_together={('filter_item', 'language')},
        ),
        migrations.AddIndex(
            model_name='filteritem',
            index=models.Index(fields=['table_filter', 'item_key'], name='filter_item_table_f_d87578_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filteritem',
            unique_together={('table_filter', 'item_key')},
        ),
    ]
