# Generated by Django 4.2 on 2024-10-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteritem',
            name='table_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tablefilter'),
        ),
        migrations.AlterField(
            model_name='tablefield',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.datatype'),
        ),
        migrations.AlterField(
            model_name='tenanttable',
            name='table_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tabletype'),
        ),
        migrations.AlterField(
            model_name='tenanttable',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tenant'),
        ),
        migrations.AlterField(
            model_name='tenanttablefield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tablefield'),
        ),
        migrations.AlterField(
            model_name='tenanttablefield',
            name='field_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.fieldorder'),
        ),
        migrations.AlterField(
            model_name='tenanttablefilter',
            name='table_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tablefilter'),
        ),
    ]
