# Generated by Django 4.2 on 2024-10-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenanttablefield',
            unique_together={('field', 'tenant_table')},
        ),
    ]
