# Generated by Django 4.2 on 2024-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_alter_tenanttablefield_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefilter',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Indicated whether the filter items are given from external url'),
        ),
        migrations.AddField(
            model_name='tablefilter',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
