# Generated by Django 4.2 on 2024-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_tablefilter_is_external_tablefilter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefilter',
            name='placeholder',
            field=models.CharField(default='Select', max_length=255),
        ),
    ]
