# Generated by Django 4.2 on 2024-10-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_tablefilter_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablefilter',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='filterlocalization',
            name='placeholder',
            field=models.CharField(default='Select', max_length=255),
        ),
    ]
