# Generated by Django 4.2 on 2024-10-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_remove_tablefilter_placeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteritem',
            name='field_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='metadata.fieldorder'),
            preserve_default=False,
        ),
    ]
