# Generated by Django 4.2 on 2024-10-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_alter_filteritem_field_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteritem',
            name='field_order',
        ),
    ]
