# Generated by Django 4.2 on 2024-10-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_remove_filteritem_field_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteritem',
            name='field_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='metadata.fieldorder'),
            preserve_default=False,
        ),
    ]
