# Generated by Django 4.2 on 2024-10-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_plantentitylocalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Key for the asset category (e.g., 'stats').", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the asset is currently active.')),
                ('is_external', models.BooleanField(default=False, help_text='Indicated whether the asstes items are given from external url')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Table Assets',
                'db_table': 'table_asset',
            },
        ),
        migrations.CreateModel(
            name='TableAssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Key for the asset item (e.g., 'snapshots').", max_length=50)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the asset is currently active.')),
                ('is_external', models.BooleanField(default=False, help_text='Indicated whether the asstes items are given from external url')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tableasset')),
            ],
            options={
                'verbose_name_plural': 'Table Asset Items',
                'db_table': 'table_asset_item',
            },
        ),
        migrations.CreateModel(
            name='TenantTableAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the asset item is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.fieldorder')),
                ('table_asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tableasset')),
                ('tenant_table', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.tenanttable')),
            ],
            options={
                'verbose_name_plural': 'Tenant Table Asset',
                'db_table': 'tenant_table_asset',
            },
        ),
        migrations.CreateModel(
            name='TableAssetLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Localized title of the asset.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Localized description of the asset.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='metadata.tableasset')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language')),
            ],
            options={
                'verbose_name_plural': 'Table Asset Localizations',
                'db_table': 'table_asset_localization',
                'unique_together': {('asset', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TableAssetItemLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Localized title of the asset item.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Localized description of the asset item.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.tableassetitem')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language')),
            ],
            options={
                'verbose_name_plural': 'Table Asset Item Localizations',
                'db_table': 'table_asset_item_localization',
                'unique_together': {('asset_item', 'language')},
            },
        ),
    ]
