# Generated by Django 4.2 on 2024-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_feedbackform_formfield_tenantfeedbackform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackformfielditemlocalization',
            name='color',
            field=models.CharField(blank=True, help_text='hex color code of the item', max_length=255, null=True),
        ),
    ]
