# Generated by Django 4.2 on 2024-11-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_feedbackformfielditemlocalization_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackformfielditem',
            name='color',
            field=models.CharField(blank=True, help_text='hex color code of the item', max_length=255, null=True),
        ),
    ]
