# Generated by Django 4.2 on 2024-12-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_feedbackformfielditem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenanttablefilter',
            name='default',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
