# Generated by Django 4.2 on 2025-02-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_tenanttablefilter_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTableAssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the asset item is currently active for this tenant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tenant_items', to='metadata.tableassetitem')),
                ('tenant_table_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_asset_items', to='metadata.tenanttableasset')),
            ],
            options={
                'verbose_name_plural': 'Tenant Table Asset Items',
                'db_table': 'tenant_table_asset_item',
                'unique_together': {('tenant_table_asset', 'asset_item')},
            },
        ),
    ]
