# Generated by Django 4.2 on 2025-07-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_taggroup_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Localized name of the tag.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Localized description of the tag.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tag_localization', to='metadata.tag')),
            ],
            options={
                'verbose_name_plural': 'Tag Localizations',
                'db_table': 'tag_localization',
            },
        ),
        migrations.CreateModel(
            name='TagGroupLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Localized name of the tag group.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Localized description of the tag group.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language')),
                ('tag_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tag_group_localization', to='metadata.taggroup')),
            ],
            options={
                'verbose_name_plural': 'Tag Group Localizations',
                'db_table': 'tag_group_localization',
            },
        ),
        migrations.AddIndex(
            model_name='taglocalization',
            index=models.Index(fields=['tag', 'language'], name='tag_localiz_tag_id_5e48fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taglocalization',
            unique_together={('tag', 'language')},
        ),
        migrations.AddIndex(
            model_name='taggrouplocalization',
            index=models.Index(fields=['tag_group', 'language'], name='tag_group_l_tag_gro_6fb12c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taggrouplocalization',
            unique_together={('tag_group', 'language')},
        ),
    ]
